### ISSUE TITLE
Visually distinct public key hash

### ISSUE THREAD

**Issue by nbyoung** [8bitgeek/hive#18]
Would it be practical to make the public key hash visually distinct from DHT node id? Some simple ideas are:
* Length
  * For human convenience, ideally shorter
* Capitalisation (e.g., ALL CAPS)
* Conventional prefix or suffix, e.g., PUBLICXXXX

In a demo of `hive-node -G` the node id and public key hash have indistinguishable visual appearance. Identifying which is which relies on context or labeling. Users might easily get confused, especially newbies who are new to the concepts.

![image](https://user-images.githubusercontent.com/3386293/192149504-657e738e-36a2-4959-929e-d9b902a54346.png)

**Comment by 8bitgeek** [comment]
I'm not sure if we even want the end user to necessarily know there is a public/private key, let alone what it is - I dunno, maybe they can see it if they drill down into the other user's profile or something. I think this whole process should be as transparent as possible to the end user. So transparent, they don't even know it's there.

What I think we want, is for the user, to be assured that this is the right guy through out-of-band means, or other yet-to-be-determined method or convention. How do you know it's the right guy when you friend somebody on twitter or other platforms?

And then once the user "friends" the other guy, then, from that point forward that other guy's public key is persistently stored (where/how tbd), and is verified by an encoded-secret exchange against that initial public key, whenever a verification of identity is required.

I don't think we want the end user to be messing around with this "hive-node" utility at this level. At most, maybe it makes up part of the back-end to a locally hosted web interface or so.

In that vein, I'm thinking that the output from this utility should be json, with maybe a cli option for other a tabular format or so.

**Comment by 8bitgeek** [comment]
Thinking about this a little more. I think we need multiple utilities for testing and development, starting with hive-node, which maybe should be renamed to "hive-dir", to strictly test directory operations. The utility should support command line parameters for easy test scripting. Then we also want another utility, for instance, to test an http front-end interface. And similarly a utility to test each discreet feature, until finally we roll them all up into a main "hive-node" feature. 

@nbyoung  What are your thoughts on that?

**Comment by nbyoung** [comment]
Your idea of canonical input/output language for these command-line modules addresses my original question directly, and lays a solid foundation for your follow-on points.

I was forgetting that end users would not be the audience for this command example. I also still agree with your general idea that end users should ordinarily be unconcerned with technical implementation details during everyday use, e.g., public key identity. "Trust, but verify" comes to mind as a guiding principle. Most users should simply trust most functions most of the time, but any user should be able to verify any function at any time.

Comments are big part of my attraction to YAML as an input/output language, which could be useful, for example, in including human-only annotations in command output without bunging up the pipeline. YAML comments originally gained my attention for configuration files. YAML also offers more natural formatting features over JSON, e.g., bulleted lists, etc. JSON is a proper subset, so there's no urgency for YAML, and I'm not married to it, but it could offer some nice capabilities for incrementally more effort.

Your last point is the most important. What are the fundamental functional building blocks? I don't want to try addressing them superficially. A topic for sync-up?
